---
title: "Unsupervised Classification of Satellite Images"
---

**Date**: 2023-08-29, 13:30–15:00 and 2023-08-29, 15:30–17:00

**Speaker**: Krzysztof Dyba

**Key Concepts Learned**:

Basics of unsupervised satellite image classification
Preparation and analysis of Landsat raster data in R
Grouping methods in unsupervised learning and their practical execution
Crafting and interpreting land cover maps
Tackling challenges in cluster selection, result interpretation, and validation
This workshop was particularly beneficial as it required no prior labeling of data, making it a versatile and accessible approach for my initial forays into satellite image analysis. It was a skillful blend of theory and practice, ensuring that we understood both the "how" and "why" of the techniques we employed.

The "Unsupervised classification (clustering) of satellite images" workshop, introduced me to the essential techniques of grouping pixels in satellite imagery based on their spectral information. The session was an engaging introduction to the practical applications of unsupervised classification in environmental science, land cover mapping, and emergency response.

## Course Tutorial

In our tutorial with "Clustering.Rmd," we went through the step-by-step process of clustering analysis in R. The tutorial was comprehensive, covering data preparation, execution of clustering algorithms, and the creation of land cover maps.

<iframe src="material/Clustering.html" width="100%" height="400"></iframe>

## Practical Exercise 

Hands on the practical exercise to cement the concepts covered in the tutorial. We were tasked with applying our new knowledge to classify a new set of satellite data, confronting real-world challenges such as selecting an appropriate number of clusters and validating the classification results.

<iframe src="material/task.html" width="100%" height="400"></iframe>

## Reflections on the Workshop

Attending this workshop has been an enlightening experience, revealing the potential of unsupervised classification to contribute to critical areas of research and application. The guidance provided during the workshop addressed the common challenges faced in unsupervised classification, offering valuable insights into overcoming them.

## Materials

[Course overview](https://pretalx.earthmonitor.org/opengeohub-summer-school-2023/talk/DDABRT/)
[Github](https://github.com/kadyb/OGH2023)
[Video](https://doi.org/10.5446/63125#t=00:00,03:18)